#!/bin/sh
set -e

case "$1" in
    remove|purge)
        rm -rf /opt/whatever2sbom/venv
        ;;
esac

# Only drop user-supplied plugins on a full purge.
case "$1" in
    purge)
        rm -rf /opt/whatever2sbom/plugins
        ;;
esac

exit 0
