#!/bin/sh
set -e

VENV=/opt/whatever2sbom/venv
WHEELS=/opt/whatever2sbom/wheels

if [ ! -d "$VENV" ]; then
    python3 -m venv "$VENV"
fi

"$VENV/bin/pip" install --no-index --find-links "$WHEELS" --upgrade whatever2sbom

exit 0
